applications:
    - type: CustomApplication
      class: MetadataFilenameParser
      extension: app
aura:
    - type: AuraDefinitionBundle
      class: MetadataFilenameParser
classes:
    - type: ApexClass
      class: MetadataFilenameParser
      extension: cls
components:
    - type: ApexComponent
      class: MetadataFilenameParser
      extension: component
connectedApps:
    - type: ConnectedApp
      class: MetadataFilenameParser
customMetadata:
    - type: CustomMetadata
      class: MetadataFilenameParser
dashboards:
    - type: Dashboard
      class: MetadataFilenameParser
dataSources:
    - type: ExternalDataSource
      class: MetadataFilenameParser
documents:
    - type: Document
      class: DocumentParser
email:
    - type: EmailTemplate
      class: MetadataFolderParser
homePageComponents:
    - type: HomePageComponent
      class: MetadataFilenameParser
labels:
    - type: CustomLabel
      class: CustomLabelsParser
      extension: labels
      args:
            - './sf:labels'
    - type: CustomLabels
      class: MetadataFilenameParser
      extension: labels
layouts:
    - type: Layout
      class: MetadataFilenameParser
      extension: layout
letterhead:
    - type: Letterhead
      class: MetadataFilenameParser
matchingRules:
    - type: MatchingRule
      class: MetadataXmlElementParser
      extension: matchingRule
      args:
            - './sf:matchingRules'
objects:
    - type: CustomObject
      class: CustomObjectParser
      extension: object
    - type: BusinessProcess
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:businessProcesses'
    - type: CompactLayout
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:compactLayouts'
    - type: CustomField
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:fields'
    - type: FieldSet
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:fieldSets'
    - type: ListView
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:listViews'
    - type: NamedFilter
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:namedFilters'
    - type: RecordType
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:recordTypes'
    - type: SharingReason
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:sharingReasons'
    - type: ValidationRule
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:validationRules'
    - type: WebLink
      class: MetadataXmlElementParser
      extension: object
      args:
            - './sf:webLinks'
objectTranslations:
    - type: CustomObjectTranslation
      class: MetadataFilenameParser
      extension: objectTranslation
pages:
    - type: ApexPage
      class: MetadataFilenameParser
      extension: page
profiles:
    - type: Profile
      class: MetadataFilenameParser
      extension: profile
permissionsets:
    - type: PermissionSet
      class: MetadataFilenameParser
quickActions:
    - type: QuickAction
      class: MetadataFilenameParser
      extension: quickAction
remoteSiteSettings:
    - type: RemoteSiteSetting
      class: MetadataFilenameParser
reportTypes:
    - type: ReportType
      class: MetadataFilenameParser
reports:
    - type: Report
      class: MetadataFolderParser
scontrols:
    - type: Scontrol
      class: MetadataFilenameParser
staticresources:
    - type: StaticResource
      class: MetadataFilenameParser
      extension: resource
tabs:
    - type: CustomTab
      class: MetadataFilenameParser
translations:
    - type: Translations
      class: MetadataFilenameParser
triggers:
    - type: ApexTrigger
      class: MetadataFilenameParser
      extension: trigger
weblinks:
    - type: CustomPageWebLink
      class: MetadataFilenameParser
workflows:
    - type: WorkflowAlert
      class: MetadataXmlElementParser
      extension: workflow
      args:
            - './sf:alerts'
    - type: WorkflowFieldUpdate
      class: MetadataXmlElementParser
      extension: workflow
      args:
            - './sf:fieldUpdates'
    - type: WorkflowRule
      class: MetadataXmlElementParser
      extension: workflow
      args:
            - './sf:rules'
